services:
  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_DB: shikoudb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresdb
    ports:
      - "5432:5432"
    networks:
      - bd

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shikoudb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgresdb
    volumes:
      - ./backend:/app
      - /app/build
    networks:
      - app-network
      - bd
    depends_on:
      - postgres

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/project
      - /project/node_modules
    depends_on:
    - backend
    networks:
      - app-network

networks: # TODO: don't forget to actually connect spring with vue, silly (for delik)
  app-network:
    driver: bridge
  bd:
    driver: bridge